In [1]:
import numpy as np
import os
import json
import cv2

In [2]:
import numpy as np

npz_file_path = '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/10195895820725132694762818055891556958.npz'

npz_data = np.load(npz_file_path)

print("Keys in the npz file:", npz_data.files)

for key in npz_data.files:
    print("Data for key:", key)
    print(npz_data[key]) 


Keys in the npz file: ['data']
Data for key: data
[[ 144  144  144 ... 3338 3346 3361]
 [ 144  144  144 ... 3348 3354 3340]
 [ 144  144  144 ... 3357 3362 3343]
 ...
 [ 144  144  144 ...  203  200  197]
 [ 144  144  144 ...  202  201  198]
 [ 144  144  144 ...  202  201  199]]


In [7]:
import json

json_file = '/raid/mpsych/OMAMA/DATA/data/2d/metadata/2516607317508729065302487485215748730.json'

with open(json_file, 'r') as f:
    data = json.load(f)

print(data)


{'PatientID': 'DH4A8TAA71SI', 'View': 'cranio-caudal', 'WindowCenter': [2413.0, 2455.0, 2359.0], 'WindowWidth': [900.0, 750.0, 1050.0], 'WindowCenterWidthExplanation': ['NORMAL', 'HARDER', 'SOFTER'], 'ImagerPixelSpacing': [0.1, 0.1], 'ImageLaterality': 'R', 'coords': [1832.0, 491.0, 2122.0, 783.0], 'score': 0.036172762513160706, 'label': 'IndexCancer'}


In [1]:
import os
import json
import numpy as np

# Paths to the folders
npz_folder = '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images'
json_folder = '/raid/mpsych/OMAMA/DATA/data/2d/metadata/'

# Function to read JSON files
def read_json(file_path):
    with open(file_path, 'r') as f:
        data = json.load(f)
    return data

# Lists to store filenames for cancer and non-cancer cases
cancer_files = []
non_cancer_files = []

# Function to classify NPZ files
def classify_npz_files():
    # Read JSON files
    json_files = os.listdir(json_folder)
    files_loaded = 0
    for json_file in json_files:
        if not json_file.endswith('.json'):
            continue
        json_data = read_json(os.path.join(json_folder, json_file))
        
        # Extract label and filename
        label = json_data['label']
        filename = json_file.replace('.json', '.npz')
        
        # Match with NPZ files
        npz_file_path = os.path.join(npz_folder, filename)
        if os.path.exists(npz_file_path):
            # Classify based on label
            if label == 'NonCancer':
                if len(non_cancer_files) < 10:
                    non_cancer_files.append(npz_file_path)
                    files_loaded += 1
            else:
                if len(cancer_files) < 10:
                    cancer_files.append(npz_file_path)
                    files_loaded += 1

            if files_loaded >= 20:
                break
        else:
            print(f"NPZ file corresponding to {json_file} not found.")

# Classify NPZ files
classify_npz_files()

# Display the loaded filenames for cancer and non-cancer cases
print("Cancer Files:")
print(cancer_files)
print("\nNon-Cancer Files:")
print(non_cancer_files)


Cancer Files:
['/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/111370409263394801220515457841906602867.npz', '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/324258317749283127335955086672852457512.npz', '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/2516607317508729065302487485215748730.npz', '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/252981154439316961700476552598519903513.npz', '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/5389248068661092315642552000766157738.npz', '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/254268082136764343104834597208671411178.npz', '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/280777852456518079909499436494673249767.npz', '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/308344774958862409794762996669884777743.npz', '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/138330243972846942151547701883445455419.npz', '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/17298077669114840792732614849309934665.npz']

Non-Cance

In [6]:
import os
import json
import numpy as np

# Paths to the folders
npz_folder = '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images'
json_folder = '/raid/mpsych/OMAMA/DATA/data/2d/metadata/'

# Function to read JSON files
def read_json(file_path):
    with open(file_path, 'r') as f:
        data = json.load(f)
    return data

# Lists to store filenames for cancer, non-cancer, and unknown cases
cancer_files = []
non_cancer_files = []
unknown_files = []

# Function to classify NPZ files
def classify_npz_files():
    # Read JSON files
    json_files = os.listdir(json_folder)
    files_loaded = 0
    for json_file in json_files:
        if not json_file.endswith('.json'):
            continue
        json_data = read_json(os.path.join(json_folder, json_file))
        
        # Extract label and filename
        label = json_data['label']
        filename = json_file.replace('.json', '.npz')
        
        # Match with NPZ files
        npz_file_path = os.path.join(npz_folder, filename)
        if os.path.exists(npz_file_path):
            # Classify based on label
            if label == 'NonCancer':
                if len(non_cancer_files) < 10:
                    non_cancer_files.append(npz_file_path)
                    files_loaded += 1
            elif label == 'Unknown':
                    unknown_files.append(npz_file_path)
                    files_loaded += 1
            else:
                if len(cancer_files) < 10:
                    cancer_files.append(npz_file_path)
                    files_loaded += 1                  
            if files_loaded >= 30:  # Changed to 30 to load 10 files for each label
                break
        else:
            print(f"NPZ file corresponding to {json_file} not found.")

# Classify NPZ files
classify_npz_files()

# Display the loaded filenames for cancer, non-cancer, and unknown cases
print("Cancer Files:")
print(cancer_files)
print("\nNon-Cancer Files:")
print(non_cancer_files)
print("\nUnknown Files:")
print(unknown_files)


Cancer Files:
['/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/111370409263394801220515457841906602867.npz', '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/2516607317508729065302487485215748730.npz', '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/5389248068661092315642552000766157738.npz', '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/254268082136764343104834597208671411178.npz', '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/280777852456518079909499436494673249767.npz', '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/308344774958862409794762996669884777743.npz', '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/223561688865123578737772129108349825620.npz', '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/321482521839964890685926574197061308558.npz', '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/19854444338148038897579928728820429516.npz', '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images/115743812159712201628967037461962482541.npz']

Non-Cance

In [10]:
import json

json_file = '/raid/mpsych/OMAMA/DATA/data/2d/metadata/321482521839964890685926574197061308558.json'

with open(json_file, 'r') as f:
    data = json.load(f)

print(data)


{'PatientID': 'DHE48PD8174D', 'View': 'cranio-caudal', 'WindowCenter': [3229.0, 3271.0, 3163.0], 'WindowWidth': [900.0, 750.0, 1050.0], 'WindowCenterWidthExplanation': ['NORMAL', 'HARDER', 'SOFTER'], 'ImagerPixelSpacing': [0.09409090909091, 0.09409090909091], 'ImageLaterality': 'L', 'coords': [10.0, 992.0, 308.0, 1395.0], 'score': 0.9378398656845093, 'label': 'IndexCancer'}


In [11]:
# Verify labels by comparing with JSON files
def verify_labels(file_list, expected_label):
    for file_path in file_list:
        filename = os.path.basename(file_path)
        json_file_path = os.path.join(json_folder, filename.replace('.npz', '.json'))
        if os.path.exists(json_file_path):
            json_data = read_json(json_file_path)
            actual_label = json_data['label']
            if actual_label != expected_label:
                print(f"Incorrect label for file {filename}: Expected {expected_label}, Actual {actual_label}")
        else:
            print(f"JSON file not found for {filename}")

# Verify labels for cancer files
print("Verifying labels for cancer files:")
verify_labels(cancer_files, 'Cancer')

# Verify labels for non-cancer files
print("\nVerifying labels for non-cancer files:")
verify_labels(non_cancer_files, 'NonCancer')

# Verify labels for unknown files
print("\nVerifying labels for unknown files:")
verify_labels(unknown_files, 'Unknown')

Verifying labels for cancer files:
Incorrect label for file 111370409263394801220515457841906602867.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 2516607317508729065302487485215748730.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 5389248068661092315642552000766157738.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 254268082136764343104834597208671411178.npz: Expected Cancer, Actual PreIndexCancer
Incorrect label for file 280777852456518079909499436494673249767.npz: Expected Cancer, Actual PreIndexCancer
Incorrect label for file 308344774958862409794762996669884777743.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 223561688865123578737772129108349825620.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 321482521839964890685926574197061308558.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 19854444338148038897579928728820429516.npz: Expected Cancer, Actual IndexCancer
Incorrect 

In [18]:
import os
import json
import numpy as np

# Paths to the folders
npz_folder = '/raid/mpsych/OMAMA/DATA/data/2d_resized_512/images'
json_folder = '/raid/mpsych/OMAMA/DATA/data/2d/metadata/'

# Function to read JSON files
def read_json(file_path):
    with open(file_path, 'r') as f:
        data = json.load(f)
    return data

# Lists to store filenames for cancer, non-cancer, and unknown cases
cancer_files = []
non_cancer_files = []
unknown_files = []

# Function to classify NPZ files
def classify_npz_files():
    # Read JSON files
    json_files = os.listdir(json_folder)
    for json_file in json_files:
        if not json_file.endswith('.json'):
            continue
        json_data = read_json(os.path.join(json_folder, json_file))
        
        # Extract label and filename
        label = json_data['label']
        filename = json_file.replace('.json', '.npz')
        
        # Match with NPZ files
        npz_file_path = os.path.join(npz_folder, filename)
        if os.path.exists(npz_file_path):
            # Classify based on label
            if label == 'NonCancer':
                non_cancer_files.append(npz_file_path)
            elif label == 'Unknown':
                unknown_files.append(npz_file_path)
            else:
                cancer_files.append(npz_file_path)                 
        else:
            print(f"NPZ file corresponding to {json_file} not found.")

# Classify NPZ files
classify_npz_files()

# Print the number of total files loaded
total_files_loaded = len(cancer_files) + len(non_cancer_files) + len(unknown_files)
print("Total files loaded:", total_files_loaded)


Total files loaded: 163568


In [22]:
# Verify labels by comparing with JSON files
def verify_labels(file_list, expected_label):
    for file_path in file_list:
        filename = os.path.basename(file_path)
        json_file_path = os.path.join(json_folder, filename.replace('.npz', '.json'))
        if os.path.exists(json_file_path):
            json_data = read_json(json_file_path)
            actual_label = json_data['label']
            if actual_label != expected_label:
                print(f"Incorrect label for file {filename}: Expected {expected_label}, Actual {actual_label}")
        else:
            print(f"JSON file not found for {filename}")

# Verify labels for cancer files
print("Verifying labels for cancer files:")
verify_labels(cancer_files, 'Cancer')

# Verify labels for non-cancer files
print("\nVerifying labels for non-cancer files:")
verify_labels(non_cancer_files, 'NonCancer')

# Verify labels for unknown files
print("\nVerifying labels for unknown files:")
verify_labels(unknown_files, 'Unknown')

Verifying labels for cancer files:
Incorrect label for file 111370409263394801220515457841906602867.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 2516607317508729065302487485215748730.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 5389248068661092315642552000766157738.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 254268082136764343104834597208671411178.npz: Expected Cancer, Actual PreIndexCancer
Incorrect label for file 280777852456518079909499436494673249767.npz: Expected Cancer, Actual PreIndexCancer
Incorrect label for file 308344774958862409794762996669884777743.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 223561688865123578737772129108349825620.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 321482521839964890685926574197061308558.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 19854444338148038897579928728820429516.npz: Expected Cancer, Actual IndexCancer
Incorrect 

Incorrect label for file 248848405561101601867113685775737520020.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 34942791907349410314776654823549711553.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 39050746979410732930449139576406630931.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 216910718819815180174407881745027456696.npz: Expected Cancer, Actual PreIndexCancer
Incorrect label for file 214708827412936673420664136155097475049.npz: Expected Cancer, Actual PreIndexCancer
Incorrect label for file 19347222347345979914338272940439424295.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 83470948413705716359752235211512154075.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 232750261313546016366044303602243505660.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 79769472473055904623279698317129561442.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 51399802538781866645

Incorrect label for file 165736843914902153834507797242876900834.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 254833267527166658225385022392854002586.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 317368023404349311836009353363862087072.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 326749961775837035454814692831435878731.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 4658575872933995277367172784101477744.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 3162726378130095418472579500491705388.npz: Expected Cancer, Actual PreIndexCancer
Incorrect label for file 250090543481962458114861051828201468709.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 110206693641978099883207074615005044086.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 156291455585757620993843300041184129702.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 2048845691183901693757

Incorrect label for file 162347282316273341036780357817238633767.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 313031876578466019203098914022539668445.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 86370192730522026655278480721458313799.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 312279489481696268322983113728422005165.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 228406627409608691032470094878748348738.npz: Expected Cancer, Actual PreIndexCancer
Incorrect label for file 41292001761967860830814850852999568581.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 12972127059063997509046475984527012417.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 86136062558788126086889789984475826262.npz: Expected Cancer, Actual IndexCancer
Incorrect label for file 193633857020502102458136115049357168387.npz: Expected Cancer, Actual PreIndexCancer
Incorrect label for file 2601789830780464336


Verifying labels for unknown files:


In [21]:
def verify_labels(file_list, expected_labels):
    for file_path in file_list:
        filename = os.path.basename(file_path)
        json_file_path = os.path.join(json_folder, filename.replace('.npz', '.json'))
        if os.path.exists(json_file_path):
            json_data = read_json(json_file_path)
            actual_label = json_data['label']
            if actual_label not in expected_labels:
                print(f"Incorrect label for file {filename}: Expected one of {expected_labels}, Actual {actual_label}")
        else:
            print(f"JSON file not found for {filename}")

# Define expected labels for cancer files
expected_cancer_labels = ['IndexCancer', 'PreIndexCancer']

# Verify labels for cancer files
print("Verifying labels for cancer files:")
verify_labels(cancer_files, expected_cancer_labels)

Verifying labels for cancer files:
